version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - cp -r python/* .
    post_build:
      - ls -ltrah docs/
      - ls -ltrah build/
      - ls -ltrah _build/
      # - sed -i -e "s/ module</</g" docs/_build/html/**.html
      # - sed -i '/Built with/,/Docs<\/a>./d' docs/_build/html/**.html
sphinx:
   configuration: docs/source/conf.py
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs