version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - cp -r python/* .
    pre_build:
      - python -m pylint --output-format=text polymers | tee pylint.log || pylint-exit $?
      # - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.log)
      # - >
      #   if (( $(echo "${PYLINT_SCORE} >= 8.0" | bc -l) )); then
      #     COLOR=brightgreen
      #   elif (( $(echo "${PYLINT_SCORE} >= 4.0" | bc -l) )); then
      #     COLOR=yellow
      #   elif (( $(echo "${PYLINT_SCORE} >= 2.0" | bc -l) )); then
      #     COLOR=orange
      #   else
      #     COLOR=red
      #   fi
      # - curl "https://img.shields.io/badge/Pylint-${PYLINT_SCORE}-${COLOR}?logo=python&logoColor=FBE072" -o pylint.svg
    # post_build:
    #   - mv pylint.svg docs/source/_build/html/
sphinx:
   configuration: docs/source/conf.py
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - all