version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - cd python/
    post_build:
      - pwd
      - ls -ltrah
sphinx:
   configuration: python/docs/source/conf.py
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs