version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - cp -r python/* .
    pre_build:
      - PYLINT_SCORE=$(python -m pylint --output-format=text polymers | grep "Your code has been rated at" | cut -d / -f1 | rev | cut -d " " -f1 | rev)
      - >
        if [[ ${PYLINT_SCORE} > 8 ]]; then
          COLOR=brightgreen
        elif [[ ${PYLINT_SCORE} > 4 ]]; then
          COLOR=yellow
        elif [[ ${PYLINT_SCORE} > 2 ]]; then
          COLOR=orange
        else
          COLOR=red
        fi
      - curl "https://img.shields.io/badge/Pylint-${PYLINT_SCORE}-${COLOR}?logo=python&logoColor=FBE072" -o pylint.svg
    post_build:
      - mv pylint.svg docs/source/_build/html/
sphinx:
   configuration: docs/source/conf.py
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - all