version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - cp -r python/* .
    post_build:
      - ls -ltrah docs/source/_build/
      - ls -ltrah docs/source/_build/html/
      - sed -i -e "s/ module</</g" docs/source/_build/html/*.html
      - sed -i -e "/Built with/,/Docs<\/a>./d" docs/source/_build/html/*.html
sphinx:
   configuration: docs/source/conf.py
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs