version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_create_environment:
      - cp -r python/* .
    post_build:
      - sed -i 's/module</</g' build/html/*.html
      - sed -i '/Built with/,/Docs<\/a>./d' build/html/*.html
sphinx:
   configuration: docs/source/conf.py
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs