[package]
name = "polymers"
version = "0.0.2"
edition = "2021"
description = "Polymers Modeling Library"
license = "BSD-3-Clause"
keywords = ["python", "rust", "polymers"]

[lib]
crate-type = ["staticlib", "cdylib"]

[dev-dependencies]
rand = "0.8.5"