name: Crates.io
on:
  push:
    tags:
      - '*'
jobs:
  cargo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: package
        run: cargo package --verbose
        working-directory: ./rust/
      - id: publish
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish --verbose
        working-directory: ./rust/