name: Docker latest
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/heads/main')
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2.1.0
        with:
          username: mrbuche
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3.2.0
        with:
          push: true
          tags: mrbuche/polymers:latest
      - run: sleep 500s
  test:
    needs: build
    runs-on: ubuntu-22.04
    container: mrbuche/polymers
    steps:
      - run: echo "placeholder"