name: Docker versioned
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2.1.0
        with:
          username: mrbuche
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2.8.0
        with:
          push: true
          tags: |
            mrbuche/polymers:${{steps.tag.outputs.tag}}
            mrbuche/polymers:latest
      - run: sleep 500s
  test:
    needs: build
    runs-on: ubuntu-22.04
    container: mrbuche/polymers
    steps:
      - run: echo "placeholder"