name: Python
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install
        working-directory: ./python/
        run: pip install .[test]
      - name: pylint
        working-directory: ./python/
        run: python -m pylint --output-format=text polymers | tee lint.log || pylint-exit $?
      - name: pytest
        working-directory: ./python/
        run: python -m pytest --verbose --cov=polymers --cov-report xml
      - name: coveralls
        run: |
          python -m pip install coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}